version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./data:/mosquitto/data
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
    restart: unless-stopped